name: 'Build Bot'

on:
  push:
    branches-ignore:
      - 'master'

jobs:
  build:
    name: 'CI Pipeline'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: 'Setup GraalVM'
        uses: DeLaGuardo/setup-graalvm@3
        with:
          graalvm-version: '20.0.0.java11'

